apiVersion: v1
kind: Pod
metadata:
  name: liveness-httppod
spec:
  containers:
  - name: container1
    image: yasirdocker/flag:latest
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
