apiVersion: v1

kind: Pod

metadata:
  name: liveness-pod
  
spec:
  containers:
  - name: container1
    image: yasirdocker/flag:latest
    ports:
    - containerPort: 80
    livenessProbe:
      exec: 
        command:
        - ls
        