apiVersion: v1
kind: Pod
metadata:
  name: podwithlivenesandreadiness
spec:
  containers:
  - name: container1
    image: yasirdocker/flag:latest
    ports:
    - containerPort: 80
    livenessProbe:
      exec:
        command:
        - ls
    readinessProbe:
      exec:
        command:
        - ls
