apiVersion: v1

kind: Service

metadata:
  name: my-service-np

spec:
  type: NodePort
  selector:
    app: rsexample
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000  # Specify the NodePort number (30000-32767) you want to use
