apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
spec:
  containers:
    - name: my-container
      image: yasirdocker/flag:latest
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
       
  volumes:
    - name: secret-volume
      secret:
        secretName: firstsecret
