apiVersion: v1
kind: Pod
metadata:
  name: pod-with-configmap
spec:
  containers:
    - name: my-container
      image: yasirdocker/flag:latest
      volumeMounts:
        - name: configmap-volume
          mountPath: /etc/config
          
  volumes:
    - name: configmap-volume
      configMap:
        name: configmap2
